<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/1
 * Time: 23:16
 */

namespace app\Controllers\sd3;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;

class Taop extends BaseController
{
    private $ws;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
        $this->ws = get_instance()->getAsynPool('ws');
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {


        $this->http_output->end('ok');
    }
}
