<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/1
 * Time: 23:16
 */

namespace app\Controllers\sd3;


use app\Controllers\BaseController;

class Taop extends BaseController
{
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {
        $this->end(123);
    }
}
