<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/7/20
 * Time: 10:19
 */

namespace app\Controllers\sd3;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;

class Upload extends  BaseController
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub

    }

    public function http_perform()
    {
//        $raw = $this->http_input->getAllPost();
//        print_r($raw);
//        $res['url'] = sprintf('https://img.oranzh.cc/%s',$raw['object']);
//        $this->end($res,0,false);
        $this->http_output->setCookie('blue','',time()-1);
        $this->http_output->end('ok');
    }

}
