<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/7/26
 * Time: 10:18
 */

namespace app\Controllers\sd3;


use app\Controllers\BaseController;

class Validate extends BaseController
{
    private $qq;
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->qq = get_instance()->getAsynPool('qq');
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {
        $data = [
            'aid' => 2094870261,
            'AppSecretKey' => '0805CswKSHB5KV-xDTN4oqw**',
            'Ticket' => 't02sxTzyqPy2uszO1-aoJ8ekPJ51_2u-dDonHKk8zMzqF5PrXFTAJwUluNWldgSEXyfjRn5sIYTaTVBQX4e3rvPtIuzry-u1WffiB1xFdaAF_FmWKraZZI9Hg**',
            'Randstr' => 'jklixj1568s1df35sDFS',
            'UserIP' => '52.231.159.31'

        ];
        $response = $this->qq->httpClient
            ->setQuery($data)
            ->coroutineExecute('/ticket/verify');
        $this->end($response['body']);
    }


}