<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/7/26
 * Time: 10:18
 */

namespace app\Controllers\sd3;


use app\Controllers\BaseController;

class Validate extends BaseController
{
    private $qq;
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->qq = get_instance()->getAsynPool('qq');
    }

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {
        $ticket = $this->http_input->getPost('ticket');
        $randstr = $this->http_input->getPost('randstr');
        $userIP = $this->http_input->header('x-real-ip');
        $data = [
            'aid' => 2094870261,
            'AppSecretKey' => '0805CswKSHB5KV-xDTN4oqw**',
            'Ticket' => $ticket,
            'Randstr' => $randstr,
            'UserIP' => $userIP,

        ];
        $response = $this->qq->httpClient
            ->setQuery($data)
            ->coroutineExecute('/ticket/verify');
        $this->end($response['body']);
    }


}