<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/6
 * Time: 12:42
 */

namespace app\Models\commit\passport;

use app\Exception\BlueWarningException;
use app\Models\dao\Passport;
use Server\CoreBase\Model;

class Register extends Model
{
    private $table = 'passport';
    private $dPassport;
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->dPassport = $this->loader->model(Passport::class,$this);
    }

    public function perform()
    {
        $params = $this->context['commit'];
        $params['create_time'] = $params['update_time'] = time();
        $passport = $this->dPassport->getFromName($params['name']);
        if (!empty($passport)) throw new BlueWarningException('用户已经存在');
        $params['password'] = password_hash($params['password'],PASSWORD_BCRYPT);
        $this->db->begin(function () use ($params)
        {
            $rows = $this->db->insert($this->table)->set($params)->query()->affected_rows();
            if ($rows != 1) throw new BlueWarningException('添加失败');
        },function (){
            throw new BlueWarningException('添加失败123');
        });
    }
}