<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/7
 * Time: 14:32
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;
use app\Models\service\Passport as sPassport;

class Friends extends BaseController
{
    private $sPassport;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->sPassport = $this->loader->model(sPassport::class,$this);
    }

    public function http_perform()
    {
        $pn = $this->http_input->get('pn');
        $pn < 1 and $pn = 1 or intval($pn);
        $res = $this->sPassport->getList($pn);
        $this->end(['list' => $res]);
    }

}