<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/8
 * Time: 9:41
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;

class History extends BaseController
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function setUp()
    {
        $this->needLogin();
    }

    public function http_perform()
    {
        $sess = $this->context['sess'];
        $uid = $this->http_input->getPost('uid');
        $tmp = ['websocket_'.$sess['id'],'websocket_'.$uid];
        sort($tmp);
        $key = implode('-',$tmp);
        $history = $this->redis->sMembers($key);
        $history = array_map(function ($v) {
            $v = json_decode($v,true);
            $v['create_time'] = date('Y-m-d H:i:s',$v['create_time']);
            return $v;
        },$history);
        array_multisort(array_column($history,'time'),SORT_DESC,$history);
        $this->end(['history' => $history]);
    }

}
