<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/6
 * Time: 22:18
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;

class IsOnline extends BaseController
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {
        $uid = $this->http_input->get('uid');
        $res = get_instance()->coroutineUidIsOnline('websocket_'.$uid);
        $this->end($res);
    }
}