<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/9
 * Time: 12:21
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;
use app\Models\commit\group\Join;
use Respect\Validation\Validator as v;

class JoinGroup extends BaseController
{
    private $cJoin;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->cJoin = $this->loader->model(Join::class,$this);
    }

    protected function setUp()
    {
       $this->needLogin();
    }

    public function http_perform()
    {
        $params = $this->verify();
        $params['passport'] = $this->context['sess']['id'];
        $this->context['commit'] = $params;
        $this->cJoin->perform();
        //$this->addSub('group_id_'.$params['group_id']);
        $this->end('ok');
    }

    private function verify()
    {
        $params = $this->input();
        v::arrayVal()->key('group_id',v::intVal()->min(1,true))->check($params);
        return $params;
    }
}