<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/6
 * Time: 16:10
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;
use app\Models\service\Passport as sPassport;
use Respect\Validation\Validator as v;


class Login extends BaseController
{
    private $sPassport;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->sPassport = $this->loader->model(sPassport::class,$this);
    }

    public function http_perform()
    {
        $params = $this->verify();
        $res = $this->sPassport->login($params['name'],$params['password']);
        $this->end($res);
    }

    private function verify()
    {
        $params = $this->http_input->getAllPost();
        v::arrayVal()->key('name', v::stringType()->length(3, 20))
            ->key('password', v::stringType()->length(6, 30))
            ->check($params);
        return $params;
    }

}