<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/6
 * Time: 15:52
 */

namespace app\Controllers\im;


use app\Controllers\BaseController;
use Server\CoreBase\ChildProxy;
use Respect\Validation\Validator as v;
use app\Models\commit\passport\Register as pRegister;

class Register extends BaseController
{
    private $Register;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->Register = $this->loader->model(pRegister::class,$this);
    }

    public function http_perform()
    {
        $params = $this->verify();
        $this->context['commit'] = $params;
        $this->Register->perform();
        $this->end('添加成功');
    }

    private function verify()
    {
        $params = $this->http_input->getAllPost();
        v::arrayVal()->key('name', v::stringType()->length(3, 20))
            ->key('password', v::stringType()->length(6, 30))
            ->check($params);
        return $params;
    }
}