<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/9
 * Time: 12:25
 */

namespace app\Models\commit\group;


use app\Exception\BlueWarningException;
use Server\CoreBase\Model;
use app\Models\dao\Group;
use app\Models\dao\GroupPassport;

class Join extends Model
{
    private $dGroup;
    private $dGroupPassport;
    private $table = 'group_passport';
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->dGroup = $this->loader->model(Group::class,$this);
        $this->dGroupPassport = $this->loader->model(GroupPassport::class,$this);
    }

    public function perform()
    {
        $params = $this->context['commit'];
        //1,先判断此群组是否存在
        //2,再判断此人是否已经加入此小组
        $group_info = $this->dGroup->get($params['group_id']);
        if (empty($group_info)) throw new BlueWarningException('此群组不存在,请选择其他群组加入');
        $group_pass_info = $this->dGroupPassport->getByGroupAndPassport($params['group_id'],$params['passport']);
        if (!empty($group_pass_info)) throw new BlueWarningException('您已加入此群组');
        $params['create_time'] = $params['update_time'] = time();
        $this->db->begin(function () use ($params)
        {
            $rows = $this->db->insert($this->table)->set($params)->query()->affected_rows();
            if ($rows != 1) throw new BlueWarningException('添加失败');
            $this->redis->sAdd('group_id_'.$params['group_id'],$params['passport']);
        },function (){
            throw new BlueWarningException('加入群组失败');
        });
    }
}