<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/9
 * Time: 18:23
 */

namespace app\Controllers\wss;


use app\Controllers\BaseController;

class AddSub extends BaseController
{
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function perform()
    {
        $topic = $this->client_data->topic;
        $this->addSub($topic);
    }

}