<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/9
 * Time: 17:07
 */

namespace app\Controllers\wss;


use app\Controllers\BaseController;

class SendToGroup extends BaseController
{
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function perform()
    {
        $group_id = 'group_id_'.$this->client_data->group_id;
        $content = $this->client_data->content;
        $passport_id = substr($this->uid,10);
        $this->sendPub($group_id,$content,[$this->uid]);
//        if ($this->redis->sIsMember($group_id,$passport_id)) {
//            $this->sendPub($group_id,$content,[$this->uid]);
//        } else {
//            $this->send('你不在这个群组里面,请先加入,再发消息');
//        }
    }
}