<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/9
 * Time: 12:28
 */

namespace app\Models\dao;


use Server\CoreBase\Model;

class GroupPassport extends Model
{
    private $table = 'group_passport';
    private $table_group = 'groups';
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
    }

    /**
     * @param $group_id
     * @param $passport
     * @return null
     * @throws \Throwable
     */
    public function getByGroupAndPassport($group_id,$passport)
    {
        $res = $this->db->select('*')
            ->from($this->table)
            ->where('passport',$passport)
            ->andWhere('group_id',$group_id)
            ->query()->row();
        return $res;
    }

    /**
     * @param $passport
     * @return mixed
     * @throws \Throwable
     */
    public function getGroupsByPassport($passport)
    {
        $res = $this->db->select('*')
            ->from($this->table)
            ->where('passport',$passport)
            ->query()
            ->result_array();
        return $res;
    }

    public function getGroupsByPassport2($passport)
    {
        $res = $this->db->select('*')
            ->from($this->table)
            ->innerJoin($this->table_group,'id')
            ->where($this->table.'passport',$passport)
            ->query()
            ->result_array();
        return $res;
    }
}