<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/8
 * Time: 14:04
 */

namespace app\Models\service;

use Server\CoreBase\ChildProxy;
use Server\CoreBase\Model;
use app\Models\dao\Group as dGroup;

class Group extends Model
{
    private $dGroup;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->dGroup = $this->loader->model(dGroup::class,$this);
    }

    /**
     * @param $name
     * @return mixed
     */
    public function getFromName($name)
    {
        return $this->dGroup->getFromName($name);
    }

    /**
     * @param $id
     * @return mixed
     */
    public function get($id)
    {
        return $this->dGroup->get($id);
    }

    public function getAll()
    {
        return $this->dGroup->getAll() ?? [];
    }
}