<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/8/10
 * Time: 14:32
 */

namespace app\Models\service;


use Server\CoreBase\Model;
use app\Models\dao\Group as dGroup;
use app\Models\dao\GroupPassport as dGroupPassport;
use app\Models\dao\Passport as dPassport;

class GroupPassport extends Model
{
    private $dGroup;
    private $dGroupPassport;
    private $dPassport;
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->dGroup = $this->loader->model(dGroup::class,$this);
        $this->dGroupPassport = $this->loader->model(dGroupPassport::class,$this);
        $this->dPassport = $this->loader->model(dPassport::class,$this);
    }

    /**
     * @desc 用户加入的群组
     * @param $passport
     * @return array
     */
    public function getGroupsByPassport($passport)
    {
        $groups = $this->dGroupPassport->getGroupsByPassport($passport);
        if ($groups) {
            foreach ($groups as &$v) {
                $group_info = $this->dGroup->get($v['group_id']);
                $v['group_name'] = $group_info['name'] ?? '';
                $leader_info = $this->dPassport->get($group_info['leader']);
                $v['group_leader_name'] = $leader_info['name'] ?? '';
                $v['create_time'] = date('Y-m-d H:i:s',$v['create_time']);
            }
            unset($v);
        }
        return $groups ?? [];
    }
}