<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/7/3
 * Time: 11:21
 */

namespace app\Models\service;


use app\Exception\BlueWarningException;
use app\Models\dao\MysqlDao;
use Server\CoreBase\ChildProxy;
use Server\CoreBase\Model;

class MysqlService extends Model
{
    private $mysqlDao;
    protected $redis_table = 'users';
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->mysqlDao = $this->loader->model(MysqlDao::class,$this);

    }

    public function createTable()
    {
        $res = $this->mysqlDao->createTable();
        return $res;
    }

    public function insert($data)
    {
        $res = $this->mysqlDao->insert($data);
        if ($res == 0 ) throw new BlueWarningException('写入数据失败');
    }

    public function update($data)
    {
        $res = $this->mysqlDao->update($data);
        $res = $this->mysqlDao->update2();
        return $res;
    }

    public function update2()
    {
        $res = $this->mysqlDao->update2();
        if ($res == 0 ) throw new BlueWarningException('更新数据失败');
    }

    public function incr($id)
    {
        $res = $this->mysqlDao->incr($id);
        if ($res ==0) throw new BlueWarningException('incr failed');
    }

    /**
     * @param array $id
     * @return mixed
     */
    public function in(array $id)
    {
        $res = $this->mysqlDao->in($id);
        return $res;
    }

    public function between()
    {
        $res = $this->mysqlDao->between();
        return $res;
    }

    public function select()
    {
        $res = $this->mysqlDao->select();
        return $res;
    }

    public function count()
    {
        $res = $this->mysqlDao->count();
        return $res;
    }

    public function delete()
    {
        $res = $this->mysqlDao->delete();
        if ($res ==0) throw new BlueWarningException('delete failed');
    }

    public function selectOne($id)
    {
        $tmp = $this->redis->hGet($this->redis_table,$id);
        if ($tmp) return json_decode($tmp,true);
        $res = $this->mysqlDao->selectOne($id);
        $this->redis->hSet($this->redis_table,$id,json_encode($res));
        return $res;
    }


}