<?php
/**
 * Created by PhpStorm.
 * User: lee
 * Date: 5/3/18
 * Time: 8:57 AM
 */

namespace app\Controllers;


use Server\CoreBase\ChildProxy;

class Blade extends BaseController
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function http_demo1()
    {
        if ($this->isGet()) {
            $tpl = $this->loader->view('app::page/blade/demo1/main',[]);
            $this->http_output->end($tpl);
            $this->interrupt();
        }
        var_dump($this->http_input->getAllPost());
        $this->end('ok');
    }
}