<?php
/**
 * Created by PhpStorm.
 * User: lee
 * Date: 5/3/18
 * Time: 8:57 AM
 */

namespace app\Controllers;


use Server\CoreBase\ChildProxy;

class Blade extends BaseController
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function http_perform()
    {
        if ($this->isGet()) {
            $data = [
                'msg' => 'ok',
                'content' => 'this is blade view',
            ];
            $this->getView($data);
        }
        $res = $this->http_input->getAllPost();
        //这里可以做数据处理
        $this->end($res);//返回数据
    }

    public function http_oss()
    {
        if ($this->isGet()) {
            $tpl = $this->loader->view($this->getView(),[]);
            $this->http_output->end($tpl);
            $this->interrupt();
        }
    }
}