<?php
/**
 * Created by PhpStorm.
 * User: leexiaohui(oranzh.cc@gmail.com)
 * Date: 2018/7/3
 * Time: 10:56
 */

namespace app\Controllers;


use app\Exception\BlueFatalException;
use app\Exception\BlueWarningException;
use app\Models\service\MysqlService;
use Server\CoreBase\ChildProxy;

class Sd3 extends BaseController
{
    private $mysqlService;
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        $this->redis = $this->loader->redis('redisPool');
        $this->db = $this->loader->mysql('mysqlPool',$this);
        $this->mysqlService = $this->loader->model(MysqlService::class,$this);
    }

    /**
     * SD3测试
     * sql测试
     */
    public function http_createTable()
    {
        $res = $this->mysqlService->createTable();
        $this->end($res);
    }

    public function http_insert()
    {
        $data = [
            'id' => 218,
            'user_name' => 'leexiaohui',
            'emails' => 'i@xiaohui.li',
            'num' => 9,
        ];
        $this->mysqlService->insert($data);
        $this->end('insert ok');
    }

    public function http_update()
    {
        $data = [
            'id' => 216,
            'user_name' => 'lixiaohui'
        ];
        $this->mysqlService->update($data);
        $this->end('update ok');
    }

    public function http_update2()
    {
        $this->mysqlService->update2();
        $this->end('update2 ok');
    }

    public function http_incr()
    {
        $id = $this->http_input->get('id');
        $this->mysqlService->incr($id);
        $this->end('ok');
    }

    public function http_in()
    {
        $id = [
            216,
            217,
        ];
        $res = $this->mysqlService->in($id);
        $this->end($res);
    }

    public function http_between()
    {
        $res = $this->mysqlService->between();
        $this->end($res);
    }

    public function http_all()
    {
        $res = $this->mysqlService->select();
        $this->end($res);
    }

    public function http_count()
    {
        $res = $this->mysqlService->count();
        $this->end($res);
    }

    public function http_delete()
    {
        $this->mysqlService->delete();
        $this->end('delete ok');
    }


    /**
     * 测试异常
     */
    public function http_error()
    {
        $this->end(123);
        $this->interrupt();
    }

    public function http_warn()
    {
        throw  new BlueWarningException('Warning Error');
    }

    public function http_fatal()
    {
        throw new BlueFatalException('fatal error');
    }

}