<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/8
 * Time: 22:50
 */

namespace app\Models;


use Server\CoreBase\ChildProxy;
use Server\CoreBase\Model;

class BaseModel extends Model
{
    public function __construct($proxy = ChildProxy::class)
    {
        parent::__construct($proxy);
    }

    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
        //$this->db = $this->loader->mysql('wss',$this);
    }

    public function jundgeRow($row,$message = '')
    {

    }

    public function jundgeResult($result,$message = '')
    {

    }
}